### ISSUE TITLE
为什么读取不了百度云目录呢？

### ISSUE THREAD

**Issue by KSD16** [yaronzz/BaiduYunToAliYun#22]
![图片](https://user-images.githubusercontent.com/47467349/140502527-20adde3b-e2a4-495a-a941-2b0c03a8da3e.png)

**Comment by atfa** [comment]
我也遇到这个错误了，method明明就是list，但是却没有执行67行的return。

**Comment by Babyvox550** [comment]
![image](https://user-images.githubusercontent.com/13328183/179933855-36b7ff4a-4d7a-4bb4-b780-1cfb81ffbe6b.png)
Debian 出现这个提示。
