### ISSUE TITLE
请问 pip3 install b2a --upgrade 之后如何使用 b2a？

### ISSUE THREAD

**Issue by Mvbbb** [yaronzz/BaiduYunToAliYun#4]
不太懂 pip3 的使用。

我 pip3 install b2a --upgrade 之后执行 b2a 命令显示找不到此命令。请问我是缺少了哪一步吗？
![image](https://user-images.githubusercontent.com/56795364/126735640-80427d24-dc99-4918-9a00-ed1eebdf7358.png)

**Comment by yaronzz** [comment]
重装：
```
pip3 install Cython --upgrade
pip3 install BaiduPCS-Py --upgrade
pip3 install aigpy --upgrade
pip3 install b2a --upgrade
```
还是不行的话，应该是python没装好，百度一下。再不行的话用[exe](https://github.com/yaronzz/BaiduYunToAliYun/tree/main/exe)

**Comment by CHIM0** [comment]
> 不太懂 pip3 的使用。
> 
> 我 pip3 install b2a --upgrade 之后执行 b2a 命令显示找不到此命令。请问我是缺少了哪一步吗？
> ![image](https://user-images.githubusercontent.com/56795364/126735640-80427d24-dc99-4918-9a00-ed1eebdf7358.png)

可以直接运行目录下的__init__.py
<img width="400" alt="截屏2021-07-28 下午3 18 49" src="https://user-images.githubusercontent.com/38286163/127280699-5d141a9a-5f66-417e-a6e0-8c472957cca1.png">

**Comment by yz-sheldon** [comment]
请问 我在装好之后 传输过程中总是卡在这个文件 有什么解决方法吗 
![image](https://user-images.githubusercontent.com/78435363/127312363-6be67118-77a0-4253-bb95-7b92f2363ebb.png)

**Comment by CHIM0** [comment]
> 请问 我在装好之后 传输过程中总是卡在这个文件 有什么解决方法吗
> ![image](https://user-images.githubusercontent.com/78435363/127312363-6be67118-77a0-4253-bb95-7b92f2363ebb.png)

应该是有在正常下载的，只是进度条没展示（我是这个情况

**Comment by yaronzz** [comment]
> 请问 我在装好之后 传输过程中总是卡在这个文件 有什么解决方法吗
> ![image](https://user-images.githubusercontent.com/78435363/127312363-6be67118-77a0-4253-bb95-7b92f2363ebb.png)

网络不好吧，优化了下载，可以重新试下
