### ISSUE TITLE
百度云登录失败

### ISSUE THREAD

**Issue by czbcxy** [yaronzz/BaiduYunToAliYun#5]
百度云填入cookie之后一直卡住，回车没用，登录不成功，我看了源码，应该是输入的cookie没有错的，麻烦帮忙看看是不是使用错误。
![image](https://user-images.githubusercontent.com/22326117/127092357-1f9ce51b-6f00-40ca-b61d-7e0da1275880.png)

**Comment by czbcxy** [comment]
**不会是百度云屏蔽了吧，这种挖墙脚的做法，百度云肯定不会睁一只眼闭一只眼的**

**Comment by CHIM0** [comment]
我能成功登陆，不过等了估摸2，3分钟的时间，但是到了迁移文件的步骤时下载无法进行，不知道是个人设备的问题还是百度的问题
![image](https://user-images.githubusercontent.com/38286163/127280217-4f8272ab-d8ee-43c2-b76c-4e4c90c23eac.png)

**Comment by yaronzz** [comment]
> **不会是百度云屏蔽了吧，这种挖墙脚的做法，百度云肯定不会睁一只眼闭一只眼的**

用命令行试一下：b2a -b "你的key"

**Comment by yaronzz** [comment]
> 我能成功登陆，不过等了估摸2，3分钟的时间，但是到了迁移文件的步骤时下载无法进行，不知道是个人设备的问题还是百度的问题
> ![image](https://user-images.githubusercontent.com/38286163/127280217-4f8272ab-d8ee-43c2-b76c-4e4c90c23eac.png)

最新版本？其他目录也这样？

**Comment by CHIM0** [comment]
> > 我能成功登陆，不过等了估摸2，3分钟的时间，但是到了迁移文件的步骤时下载无法进行，不知道是个人设备的问题还是百度的问题
> > ![image](https://user-images.githubusercontent.com/38286163/127280217-4f8272ab-d8ee-43c2-b76c-4e4c90c23eac.png)
> 
> 最新版本？其他目录也这样？

更新了一下最新版本2021-7-28，也和2021-7-26版一样的情况，排查了一下发现是进度条没有正常工作，只有0%和100%，因为下载速度太慢了看起来像是下载无法进行，实际上可以正常下载和迁移（没有百度云会员的痛😢）

**Comment by yaronzz** [comment]
做了多线程下载，进度条应该会好看点
