### ISSUE TITLE
能打包成exe  我这边 b2a 始终安装不起

### ISSUE THREAD

**Issue by lyydhy** [yaronzz/BaiduYunToAliYun#6]
python:  3.9.6
pip: 21.2.1

**Comment by lyydhy** [comment]
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

**Comment by yaronzz** [comment]
目录下有
