### ISSUE TITLE
v2021.7.31.3 出现403

### ISSUE THREAD

**Issue by luoei** [yaronzz/BaiduYunToAliYun#7]
非常感谢作者的付出，v2021.7.31.3 出现了403错误，麻烦看下。
Info: [43] 迁移文件: /1音乐/DJ   转自：baolaMM网盘      Mac爱好者Q群：8605326/DJ散片/收费DJ/北京工体2014三月HIPHOP mashup HOUSE综合.rar
下载中:   0%|                                       | 0.00/484M [00:00<?, ?it/s]Err: 下载文件块失败：HTTP Error 403: Forbidden
Err: 下载文件块失败：HTTP Error 403: Forbidden
Err: 下载文件块失败：HTTP Error 403: Forbidden
Err: 下载文件块失败：HTTP Error 403: Forbidden
Err: 下载文件块失败：HTTP Error 403: Forbidden
Err: 下载文件块失败：HTTP Error 403: Forbidden
下载中:   0%|                                       | 0.00/484M [00:00<?, ?it/s]
Err: [错误] 下载失败!

出现了很多这个错误，这个在网页端是可以正常下载的。

**Comment by yaronzz** [comment]
fixed
